"""
A util file that merges output of pickles generated by different condor files.
"""
import pickle
import util

def merge(filename, idxSet):
  data = []
  for idx in idxSet:
    datum = pickle.load(open(filename + str(idx) + '.pkl'))
    data.append(datum)
    util.saveToFile(filename + '.pkl', data)

if __name__ == '__main__':
  merge("values", range(4))
  merge("evaluation", range(4))